.ci/before_install.sh
.ci/script.sh
.travis.yml

This PR adds support for building OpenJFX using [Travis CI](https://travis-ci.org/).
In order to make this work, the project will have to be (freely) registered with Travis. I personally login with my Github credentials to link a project when I use Travis.
Here is an example Travis build with the same configuration (just on my temporary openjfx repo):
https://travis-ci.org/brcolow/openjfx/builds/341230348
Note that the builds that are listed as "untagged-xxxxx" would not appear on this repo, that was just for testing purposes to automatically upload failed test screenshots.

Add Travis CI builds for Linux and macOS.

---

appveyor.yml

This PR adds support for building OpenJFX on Windows using [Appveyor](https://www.appveyor.com/).
In order to make this work, the project will have to be (freely) registered with Appveyor. I personally login with my Github credentials to link a project when I use Appveyor.
Here is an example build log when using this same configuration on my test openjfx repository:
https://ci.appveyor.com/project/brcolow/openjfx/build/master%20321
Currently the builds fails on Windows, but because the test results are uploaded directly to Appveyor, we can see exactly which tests fail. Here is what the test results will look like:
https://ci.appveyor.com/project/brcolow/openjfx/build/master%20319/tests

Add Appveyor CI build for Windows.

---

modules/jdk.packager/src/main/native/library/common/PosixPlatform.cpp

PosixPlatform.cpp fails to compile with GCC 6:
/<<PKGBUILDDIR>>/modules/fxpackager/src/main/native/library/common/PosixPlatform.cpp:235:10: error: 'wait' was not declared in this scope
wait();
^
This issue has been fixed in Debian.

Fix PosixPlatform.cpp compilation with GCC 6

---

build.gradle

Setting the locale to a fixed value when generating the javadoc ensures the output of the build doesn't depend on developer specific settings. This improves the [reproducibility](https://reproducible-builds.org) of the build.

Set the locale of the javadoc

---

build.gradle

This is a fix for [JDK-8200277](https://bugs.openjdk.java.net/browse/JDK-8200277) which in turn is a stopper for separating JavaFX from the JDK.
Once this is merged into the develop branch of openjfx-jdk I will send the review request on the openjfx-dev mailing list.

8200277: Compiling native media code fails when using OpenJDK build as boot JDK

---

.ci/before_install.sh
.travis.yml

This changeset is related to #45. Qt is no longer needed to build OpenJFX, Once it was required to build JFX along with WebKit.(i.e. -PCOMPILE_WEBKIT=true), but now OpenJFX WebKit uses cmake as a meta build system.

Qt-dev tools are no longer needed by OpenJFX

---

buildSrc/linux.gradle

Gradle build fails when one or more packages are not present on linux environment. Instead of throwing some useful information, the following message is shown:
```
FAILURE: Build failed with an exception.
* Where:
Script '~/Documents/openjdk-jfx/buildSrc/linux.gradle' line: 88
* What went wrong:
A problem occurred evaluating script.
> Cannot invoke method split() on null object
```
With this fix, when the build fails because of missing packages, a more informative message is shown.
```
FAILURE: Build failed with an exception.
* Where:
Script '~/Documents/openjdk-jfx/buildSrc/linux.gradle' line: 94
* What went wrong:
A problem occurred evaluating script.
> GTK2 development packages not found. If GTK2 packages are installed, please remove the build directory and try again.
```

Gradle build failure should show informative message

---

.github/sync_upstream.sh

Add the script that is used by the jenkins job to synchronise the OpenJFX mercurial repository with the fork on github. This allows others to make changes to the synchronisation process.

Add script used by jenkins job to sync with openjfx mercurial repository

---

build.gradle

This fixes issue #25 and obsoletes PR #10 which had a similar change in buildSrc/linux.gradle. 
Since that code is not used anymore, this PR has the same fix in build.gradle

add timeout to antlr processing

---

.ci/script.sh
appveyor.yml

The intent of this pull-request is to generate and then upload the debugging symbols (`*.pdb` and `*.map` files) generated during the Windows Appveyor build of OpenJFX. The files will be uploaded using [Appveyor's artifacts feature](https://www.appveyor.com/docs/packaging-artifacts/). Such debugging files are generated by switching the gradle `CONF` property from the default `Release` to `DebugNative`. These [`*.pdb` files](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger) can be used to get symbol information when debugging a JVM crash on Windows. Going forward this could be useful whenever we touch native Windows code which will definitely need to be done in order to keep JavaFX modern.
This PR is a follow-up to …

Generate PDB (debugging files) and upload them via Appveyor, use them to get native backtrace.

---

.github/README.md

This PR fixes the status badge for appveyor to point to the correct URL for loading the svg image.

Use correct status badge for appveyor

---

modules/javafx.graphics/src/main/java/com/sun/marlin/DDasher.java
modules/javafx.graphics/src/main/java/com/sun/marlin/Dasher.java
tests/system/src/test/java/test/com/sun/marlin/DashedRectTest.java

This PR corresponds to the jfx backport of the JDK-8202580 bug fix:
https://bugs.openjdk.java.net/browse/JDK-8202580
Notes: 
- (D)Dasher changes corresponds to MarlinFX 0.8.2 (upgrade to 0.9.2 later) 
- test adapted to javafx API using scene.snapshot()

Fix JDK-8202743: Dashed Stroke randomly painted incorrectly, may freeze application

---

.ci/before_install.sh
.ci/script.sh
.travis.yml
appveyor.yml

[#85, #86] Use OpenJDK for CI, use "gradle all test" instead of "gradle build".

---

build.gradle
build.properties

Fixes [JDK-8200446](https://bugs.openjdk.java.net/browse/JDK-8200446)
I'm doing it here first to make sure that the CI system for this sandbox is already using JDK 10 and thus won't be affected.

JDK-8200446: Update minimum boot JDK to 10

---

.github/CONTRIBUTING.md

Fixes #123 
Simple fix to change `master` to `develop` in CONTRIBUTING.md.
Note that this PR itself is targeted to master, as an exception, since it touches files that are only in the git repo on GitHub.

Fix CONTRIBUTING.md to indicate that PRs should use the develop branch

---

modules/javafx.web/src/main/java/com/sun/javafx/webkit/prism/WCFontImpl.java
modules/javafx.web/src/main/java/com/sun/webkit/graphics/WCFont.java
modules/javafx.web/src/main/java/com/sun/webkit/perf/WCFontPerfLogger.java
modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/FontJava.cpp
modules/javafx.web/src/test/java/test/javafx/scene/web/MathMLRenderTest.java

Hi !
This is tracked in JBS as 
- [JDK-8147476](https://bugs.openjdk.java.net/browse/JDK-8147476?jql=text%20~%20"Mathml") Rendering issues with MathML token elements.
- [JDK-8165520](https://bugs.openjdk.java.net/browse/JDK-8165520?jql=text%20~%20Mathml%20ORDER%20BY%20created%20DESC%2C%20due%20DESC%2C%20cf%5B10710%5D%20ASC) Several mathml/ DRT tests fail
- [JDK-8089878](https://bugs.openjdk.java.net/browse/JDK-8089878?jql=text%20~%20Mathml%20ORDER%20BY%20created%20DESC%2C%20due%20DESC%2C%20cf%5B10710%5D%20ASC) HTMLEditor messes up MathML markup.
- [JDK-8090887](https://bugs.openjdk.java.net/browse/JDK-8090887?jql=text%20~%20Mathml%20ORDER%20BY%20created%20DESC%2C%20due%20DESC%2C%20cf%5B10710%5D%20ASC) Support MathML.
Issue #71  was submitted for this.
Please could you review this patch : …

JDK-8147476 : Rendering issues with MathML token elements.

---

build.gradle
buildSrc/win.gradle

[JDK-8207015](https://bugs.openjdk.java.net/browse/JDK-8207015) : jlink javafx.graphics on Windows fails: PluginException: Duplicate resources

JDK-8207015: jlink javafx.graphics on Windows fails: PluginException: Duplicate resources

---

tests/system/src/test/java/test/robot/com/sun/glass/ui/monocle/TestApplication.java

I have not yet confirmed that this fixes all of the failures. In other words, I haven't actually run `gradle -PUNSTABLE_TEST=true` yet.
https://bugs.openjdk.java.net/browse/JDK-8207370

JDK-8207370 Fix failing Monocle tests (deprecated assertEquals).

---

modules/javafx.graphics/src/main/java/com/sun/glass/ui/GlassRobot.java
modules/javafx.graphics/src/main/java/javafx/scene/robot/Robot.java
tests/system/src/test/java/test/robot/javafx/scene/RobotTest.java

https://bugs.openjdk.java.net/browse/JDK-8207377

JDK-8207377 Document behavior of getPixelColor on HiDPI.

---

.ci/script.sh
.github/pr-check-whitespace.sh
.github/pr-list-files.sh

Check white-space rules as part of Travis CI build

---

modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/MonocleRobot.java

When capturing a partial region of the screen the `data` array elements have the wrong positions. This leads to an ArrayIndexOutOfBoundsException.
I introduced this error in the robot public API pull request.
This PR fixes it so that the `data` array indices match the correct pixels from the screen buffer.

JDK-8209764: JavaFX/Monocle - Partial Screen Capture Broken

---

appveyor.yml
tools/scripts/build.ps1

The script `tools\scripts\build.ps1` works for locally building OpenJFX without any additional environment setup as long as one has the [choco](https://chocolatey.org/) package manager installed. It automatically finds the location of the latest installed versions of Visual Studio and the Windows SDK and sets the necessary environment variables so that the gradle build works out-of-the-box without requiring somewhat tedious manual setup/configuration.

Add a powershell script for Windows dev, use on Appveyor.

---

modules/javafx.graphics/src/main/java/javafx/css/Stylesheet.java

I attempted to improve the javadoc comments a bit to more match the underlying code. While reading some of the code I noticed that for example in the `convertToBinary` some input / output stream might potentially not be closed properly. I would also like to fix that if desired.

JDK-8207328 Fix Stylesheet Javadocs

---

modules/javafx.graphics/src/main/native-glass/win/GlassClipboard.cpp

fixes #183 
[JDK-8210219](https://bugs.openjdk.java.net/browse/JDK-8210219)
Use our own "GLASS_HASH_SEED" constant instead of relying on an internal constant that can change out from under us (and apparently has).

JDK-8210219: GlassClipboard.cpp fails to compile with newer versions of VS2017

---

.github/pr-check-whitespace.sh
.github/pr-list-files.sh

fixes #188
In addition to separating out the listing of the files from the checking of the files, with the latter only showing the failures, I added the `--no-pager` option to `git diff` to allow it to run in the background without trying to access the terminal.

Run checkWhiteSpace without -v option

---

.github/pr-list-files.sh

This PR fixes the bug described in issue #194.
The fix is to simply add the `--no-renames` option to `git diff` when producing the list of files added or modified by a PR.
The following experimental PRs show the before/after test results for this fix:
#195 -- inject errors and verify that the renamed files are missed (not checked)
#196 -- apply the proposed fix and verify that now the injected errors in the renamed files are caught

Fix pr-list-files.sh script so renamed files are checked for white-space erorrs

---

modules/javafx.web/src/main/native/Source/WTF/wtf/Variant.h

There is a problem in the newer version(VC 14.15.26726) MSVC compiler which causes multiple symbol definition error when using lambda expression type in a function pointer argument.
Problem is already reported to Visual Studio team and it is been discussed over [here](https://developercommunity.visualstudio.com/content/problem/325062/msvs-151526726-throws-multiple-definition-error-wh.html).
The proposed workaround is to use constexpr.

JDK-8210218: WebKit build fails with newer versions of VS 2017

---

doc-files/release-notes-11.md

Here is the final draft of the JavaFX 11 release notes. The content is ready for review, but we still need to decide where to host it before it can be merged.

JDK-8210691: Deliver release notes for JavaFX 11

---

doc-files/release-notes-11.md

[JDK-8210791](https://bugs.openjdk.java.net/browse/JDK-8210791)
A [new Swing interop bug](https://bugs.openjdk.java.net/browse/JDK-8210759) was filed after the JavaFX 11 release notes were created. This bug is a new issue in FX 11 with a convenient workaround, and should be listed in the "Known Issues" section.
I also updated the release note for the other two Swing interop Known Issues for consistency and to fix a couple wording problems.
We might take this opportunity to address any other small updates to the release notes that are found during this review.

JDK-8210791: Update release notes for JavaFX 11

---

build.gradle
build.properties

Fix for JBS issue [JDK-8209966](https://bugs.openjdk.java.net/browse/JDK-8209966).
Bump the minimum JDK version needed to build JavaFX to jdk-11+28.
Note that this will not change the `javac` `--source` or --target flags (which are controlled in build.gradle by the `'sourceCompatibility'` option), which will remain at 10.
This will allow us to implement the following follow-on issues:
1. Compile with `--source 11 --target 11`
2. Stop building the old javafx.swing implementation which relies on internal API (using qualified exports on the command line)
3. Stop redistributing the Microsoft VS2017 and Windows SDK DLLs (since they are present in JDK 11).

JDK-8209966: Update minimum boot JDK to 11

---

build.gradle

Fix for JBS issue [JDK-8210093](https://bugs.openjdk.java.net/browse/JDK-8210093).
This will build the classes in the javafx.* modules with `-source 11` and `-target 11`, meaning that we can start to use JDK 11 language features. It will also cause a fast-fail if a down-rev JDK is used.

JDK-8210093: Build FX class files with -source 11 and -target 11

---

modules/javafx.graphics/src/main/native-font/freetype.c

Reduce color fringes in FreeType subpixel rendering with a direct call
to the function FT_Library_SetLcdFilter, available since FreeType 2.3.0.
Note that the runtime reference to the shared library is the versioned
file name libfreetype.so.6.
Fixes javafxports/openjdk-jfx#229

JDK-8188810: Fonts are blurry on Ubuntu 16.04 and Debian 9

---

.gitignore

Makes working on OpenJFX with IntelliJ IDEA easier and less prone to
committing unnecessary files.

Add IntelliJ IDEA related files to gitignore.

---

modules/javafx.graphics/src/main/native-glass/mac/GlassTouches.m

This fixes [JDK-8211304](https://bugs.openjdk.java.net/browse/JDK-8211304). See that JBS bug for a reproducible test case. The following evaluation is copied from JBS:
This crash is caused by a latent bug in GlassTouches.m.
There are two related problems in glass' CGEventTapCallBack method, listenTouchEvents.
1) A CGEventTapCallBack method can receive two out of band values, kCGEventTapDisabledByTimeout and kCGEventTapDisabledByUserInput, and we are only handling the first of them.
2) We unconditionally call NSEvent::eventWithCGEvent without checking that the event in question is the right type, NSEventTypeGesture in our case.
The fix is to check for kCGEventTapDisabledByUserInput in addition to kCGEventTapDisabledByTimeout and re-enable the event tap when either out of band value occurs …

JDK-8211304: [macOS] Crash on focus loss from dialog on macOS 10.14 Mojave

---

tools/scripts/build.ps1

Added gradlew --stop so that the new environment variables get used by gradle. Added chocolatey install lines for the non-webkit dependencies mentioned in the windows build instructions.
Not all dlls were being added to the published artifacts if the machine's setup didn't match the defaults in win.gradle. For example vcruntime140.dll was not being included on my machine because MSVC_REDIST_VER was not set and WINDOWS_CRT_VER was not set, resulting in the win.gradle not finding vcruntime140.dll , and not including it. My WINDOWS_CRT_VER was 141 for example where the default was 150.
The only way I could find WINDOWS_CRT_VER was by looking at the folder names. There is probably a better way.
The last change was to change -PCONF=DebugNative to -PCONF=Debug. That's because with DebugNative, …

JDK-8213619 Initialized additional environment variables.

---

modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java

* first check for a new property "javafx.cacheDir"
* if that exists, use it
* it not, use user.home directory
* if a cache directory can't be created under user.home, use java.io.tmpdir

Improvements in javafx cache for native files (JDK-8214397)

---

modules/javafx.graphics/src/main/java/com/sun/javafx/application/HostServicesDelegate.java

As per #260, here is a PR to default to `xdg-open` for document opening on UNIX systems.
It keeps the previous method as fallback in case of failure.
Little implementation note : chose to use try-catch rather than calling `which xdg-open` as this catches the nonexistence of `xdg-open` (never seen that for myself though) and also failure of `xdg-open` itself (in whatever case this might happen).
The only backwards compatibility lost here is if the users/developers were (un)knowingly relying on the lookup order of the browsers and not expecting the default browser to be used (imagining they have multiple browsers installed). I reckon this is acceptable.
---
As a side-note, while there are no tests relating to that part of the code, I still got test failures relating to prism/gtk.
Would be …

JDK-8214069 : (JavaFX) Default to xdg-open for document opening on UNIX

---

build.gradle
buildSrc/linux.gradle
buildSrc/mac.gradle
buildSrc/win.gradle
modules/javafx.web/src/main/native/Source/WebCore/PlatformJava.cmake
modules/javafx.web/src/main/native/Source/WebCore/WebCoreMacros.cmake
modules/javafx.web/src/main/native/Source/WebCore/bindings/scripts/generate-bindings-all.pl
modules/javafx.web/src/main/native/Source/WebCore/bindings/scripts/generate-bindings.pl
modules/javafx.web/src/main/native/Tools/Scripts/webkitdirs.pm

Currently JavaFX uses build tools{MSVC, GCC, Clang, CMake,..etc} from standard system paths. Adding prefix to each of those tools would help to have a custom build tools without disturbing standard tools.
This fix provides a new gradle property named BUILD_TOOLS_DOWNLOAD_SCRIPT, which could be used to point to a supplement gradle file which can have the logic to setup the custom toolchain.
In additional to provisioning toolchain prefix, this patch also has changes to javafx.web module to workaround "command line is too long" issue on windows when custom toolchain path length is long.

JDK-8211307: Add prefix to build tools paths

---

tests/system/src/test/java/test/robot/javafx/scene/RobotTest.java

(Partially? at least a step in the right direction...) resolves robot API follow-up issue [JDK-8207369](https://bugs.openjdk.java.net/browse/JDK-8207369).

JDK-8207369 Add more robot tests.

---

build.gradle
tools/scripts/build.ps1

Currently this only skips a call to chmod and is only useful for
local development builds of JavaFX. To skip Cygwin installation
one can use the "-nocygwin" flag to build.ps1 thusly:
.\tools\scripts\build.ps1 -nocygwin
The USE_CYGWIN gradle property will default to true.
Fixes #297

Allow for skipping Cygwin installation when using build.ps1 (JDK-8215629)

---

modules/javafx.base/src/main/java/com/sun/javafx/logging/PlatformLogger.java

Following methods are unimplemented, 
@Override 
public String getName() { 
throw new UnsupportedOperationException("not implemented"); 
} 
@Override 
public boolean isLoggable(System.Logger.Level level) { 
throw new UnsupportedOperationException("not implemented"); 
} 
@Override 
public void log(System.Logger.Level level, ResourceBundle bundle, String format, Object... params) { 
throw new UnsupportedOperationException("not implemented"); 
} 
@Override 
public void log(System.Logger.Level level, ResourceBundle bundle, String msg, Throwable thrown) { 
throw new UnsupportedOperationException("not implemented"); 
} 
Among those, getName() is used in JavaFX PerfLogger implementation. Implementing those would be trivial and straightforward.

JDK-8216470: Some methods of System.Logger are unimplemented in PlatformLogger

---

buildSrc/linux.gradle
modules/javafx.media/src/main/native/gstreamer/projects/linux/avplugin/Makefile
modules/javafx.media/src/main/native/gstreamer/projects/linux/fxplugins/Makefile
modules/javafx.media/src/main/native/gstreamer/projects/linux/gstreamer-lite/Makefile
modules/javafx.media/src/main/native/jfxmedia/projects/linux/Makefile

This is a fix for [JDK-8215435](https://bugs.openjdk.java.net/browse/JDK-8215435). It adds the `-Werror=trampolines` flag to the gcc build, which will fail the build if trampolines are generated for pointers to nested functions (we currently have none so this is a protection against future changes). Trampolines require executable stacks and are an anti-pattern. A corresponding JDK build change was also done for JDK 12 (see [JDK-8215400](https://bugs.openjdk.java.net/browse/JDK-8215400)).

JDK-8215435: Warn on usage of trampolines with gcc

---

modules/javafx.graphics/src/main/java/javafx/scene/Node.java
tests/system/src/test/java/test/javafx/scene/InitialNodesMemoryLeakTest.java

BugID: [JDK-8216377](https://bugs.openjdk.java.net/browse/JDK-8216377)
While working on an update for [JPro](https://www.jpro.one/), I've found out, that a unit test for a memory leak doesn't work on JavaFX11. It's a regression and doesn't happen on JavaFX8
The initial nodes of a Scene are not collected by the GC when they are removed from the Scene.
They get collected when the initial Window is closed, but this is too late and not the expected behavior.
Affected JavaFX versions: 9 10 11 develop
This happens because the listener windowShowingChangedListener is not removed from the old Window, when the Scene is Changed.
This commit makes sure, that this listener is properly removed.
This bug would create a memory leak for every node inside a window if there wouldn't be another bug.
The …

JDK-8216377: Fix memoryleak for initial nodes of Window

---

modules/javafx.web/src/main/native/Source/WebCore/platform/URLHash.h
modules/javafx.web/src/test/java/test/javafx/scene/web/MiscellaneousTest.java

"baseURL" is set to empty(null) when loading the html string using `WebEngine.loadContent` API. The URL has been used as one of the key while caching the inline CSS style content for Shadow Root(Shadow DOM). While calculating the hash value for the key, `URLHash::hash` method calls the `StringImpl::hash` method without checking for null.
It is not observed on other WebKit ports because they expose loadContent API which also takes baseURL. See [WKWebView::loadHTMLString](https://developer.apple.com/documentation/webkit/wkwebview/1415004-loadhtmlstring?language=objc).
We also should consider to provide another variant of `WebEngine.loadContent` which takes `baseURL` as a parameter.
Use to `String::hash` instead of `StringImpl::hash` from `URLHash::hash`. `String::hash` still calls …

JDK-8213806: WebView - JVM crashes for given HTML

---

modules/javafx.graphics/src/main/java/javafx/scene/Parent.java
modules/javafx.graphics/src/test/java/test/javafx/scene/ParentTest.java

If the scene graph is modified while handling a mouse event, viewOrderChildren can contain nodes which are no longer in the scene graph, causing an NPE in PickResultChooser.processOffer. This is fairly rare, and only affects parent nodes with children that have a view order set. testPickingChildNodeWithDirtyViewOrder replicates these conditions and results in the same NPE as reported in the bug report.
This solution doesn't unset the dirty bits because I'm unsure of the consequences. In the worst case the viewOrderChildren will be recalculated one extra time because of this.
An alternative solution is to keep viewOrderChildren in sync with the children list, however that would mean sorting it whenever the view order property of a child is changed (the child calls …

JDK-8205092: Added dirty check for viewOrderChildren

---

tools/scripts/build.ps1

If there are any extra parameters passed in to .\tools\scripts\build.ps1
that are not used by the script itself, then pass any additional
parameters through to gradle.
This allows for the following:
.\tools\scripts\build.ps1 -nocygwin --tests *SomeTest
Where the "--tests *SomeTest" bit is actually an argument for gradle,
not the powershell build script.

JDK-8217333: Pass additional arguments to gradle from build.ps1

---

modules/javafx.web/src/main/native/Source/ThirdParty/libxml/mac/include/libxml/xmlversion.h
modules/javafx.web/src/test/java/test/javafx/scene/web/MiscellaneousTest.java

Linked JBS: https://bugs.openjdk.java.net/browse/JDK-8218611

JDK-8218611: [DRT] fast/xslt tests fails with Unsupported encoding windows-1251

---

modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/WindowStage.java

ticket: https://bugs.openjdk.java.net/projects/JDK/issues/JDK-8217492?filter=allopenissues
I've seen it on openjfx-8, but I'm sure it can also happen on 11 and 12, because the current code isn't very reasonable. 
Sadly I don't know how to reproduce it.
Explanation:
The most relevant class for this issue is com.sun.javafx.tk.quantum.StageWindow.
When the bug happens, a StageWindow gets registered in the static HashMap platformWindows but newer get's removed.
Usually, the HashMaps gets cleared, when StageWindow.closed is called.
But when StageWindow.setPlatformWindowClosed gets called, which only happens on a WindowEvent.DESTROY,
then the reference platformWindow get nulled, but the hashmap platformWindows never gets cleaned up.
Solution:
StageWindow.setPlatformWindowClosed must be changed, …

JDK-8217492: memory leak after the event WindowEvent.DESTROY

---

modules/javafx.graphics/src/main/java/com/sun/javafx/font/directwrite/DWFactory.java
modules/javafx.graphics/src/main/java/com/sun/javafx/font/directwrite/OS.java
modules/javafx.graphics/src/main/java/com/sun/prism/GraphicsPipeline.java
modules/javafx.graphics/src/main/native-font/directwrite.cpp

GitHub issue: #66 
JBS Bug Link: https://bugs.openjdk.java.net/browse/JDK-8201539
The crash was occurring because the call to `CoUninitialize()` was done too early and resulted in `WindowsCodecs.dll` being prematurely unloaded even though `IWICImagingFactory` needed it. This caused a crash when `IWICImagingFactory` was accessed afterwards.
This is the "dispose hook approach" which adds a "dispose hook" mechanism to `GraphicsPipeline`. `DWFactory` is then taught to use this mechanism to call `CoUnitialize()` only when the `GraphicsPipeline` is being disposed (which occurs on QuantumRenderer shutdown).

JDK-8201539: WICCreateImagingFactory: defer CoUninitialize() call to thread exit (dispose hook approach)

---

modules/javafx.graphics/src/main/java/com/sun/javafx/text/ScriptMapper.java

Issue is
https://github.com/javafxports/openjdk-jfx/issues/133
Simply equal is missing.
Old Hangul is defined U+1100 to U+11FF.
http://www.unicode.org/charts/PDF/U1100.pdf

JDK-8208173: isComplexCharCode() returns false for U+11FF

---

modules/javafx.web/src/main/java/com/sun/javafx/webkit/WCMessageDigestImpl.java
modules/javafx.web/src/main/java/com/sun/webkit/perf/WCMessageDigestPerfLogger.java
modules/javafx.web/src/main/java/com/sun/webkit/security/WCMessageDigest.java
modules/javafx.web/src/main/native/Source/WebCore/PAL/pal/PlatformJava.cmake
modules/javafx.web/src/main/native/Source/WebCore/PAL/pal/crypto/java/CryptoDigestJava.cpp
modules/javafx.web/src/test/java/test/javafx/scene/web/SubresourceIntegrityTest.java
modules/javafx.web/src/test/resources/test/html/subresource-integrity-test.js

Currently [subresource integrity check](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) is not working in Linux and Windows due to missing implementation of `PAL::CryptoDigest` on those platforms. However it works in macOS because we rely on CommonCrypto based CryptoDigest implementation from WebCore. 
The goal of this PR is to implement `PAL::CryptoDigest` using `java.security.MessageDigest`., so that the subresource integrity can be supported across all the platforms.
After this, `PAL::CryptoDigest` will make use of `java.security.MessageDigest` based implementation on all platforms.
JBS link: https://bugs.openjdk.java.net/browse/JDK-8219917
This PR will fix #230.

JDK-8219917: [WebView] Sub-resource integrity check fails

---

build.gradle

This fixes [JDK-8210508](https://bugs.openjdk.java.net/browse/JDK-8210508).
Now that we have switched to using JDK 12 as the boot JDK we can (and need to) update the JDK_DOCS property to point to the JDK 12 docs so that any links from JavaFX API docs to JDK docs are generated correctly.

JDK-8210508: Update JDK_DOCS property to point to JDK 12 docs

---

build.gradle
buildSrc/src/main/groovy/com/sun/javafx/gradle/NativeCompileTask.groovy
settings.gradle

This is a preliminary review for [JDK-8215686](https://bugs.openjdk.java.net/browse/JDK-8215686) to allow the JavaFX to work with gradle 5.x, in support of upgrading to gradle 5.3 -- [JDK-8218172](https://bugs.openjdk.java.net/browse/JDK-8218172). It includes a fix for [JDK-8210509](https://bugs.openjdk.java.net/browse/JDK-8210509), since a gradle 5 build will fail without that fix.
I've run a build and test on Linux and compared the artifacts from the following builds:
gradle 4.8 without patch
gradle 4.8 with patch
gradle 5.3 with patch
All three sets of generated artifacts are identical.
The next steps are to test it on the other two platforms (Windows and Mac) and to verify the maven publishing step, which I didn't do. The (minor) changes to the maven publishing task were needed …

JDK-8215686: FX build fails using gradle 5

---

build.gradle
build.properties
gradle/legal/gradle.md
gradle/wrapper/gradle-wrapper.properties

https://bugs.openjdk.java.net/browse/JDK-8218172
This updates the gradle wrapper script to gradle 5.3. Production builds should start using 5.3 after this is merged.

JDK-8218172: Upgrade to gradle 5.3

---

build.gradle

https://bugs.openjdk.java.net/browse/JDK-8221993
This adds a task for each project, including systemTests, to test the `java` files in each sourceSet in the project. It is added as a dependency of each project's `compileTestJava` task, so that it will be run as part of `gradle test`.

JDK-8221993: Create test to validate package declarations in source files

---

build.gradle

See [JDK-8222036](https://bugs.openjdk.java.net/browse/JDK-8222036).
This fix accounts for a limitation of antlr on the Windows platform in that it won't write its output files to the proper location underneath the output directory tree unless the file name passed into antlr has Windows-style backslashes.
The fix is to ensure that we use backslashes as the file separator when running antlr.

JDK-8222036: antlr generated files written to wrong location on Windows

---

build.gradle

This fixes [JDK-8221702](https://bugs.openjdk.java.net/browse/JDK-8221702).
We should always use HTTPS to download artifacts used during a build.

JDK-8221702: Use HTTPS to download all build dependencies

---

modules/javafx.graphics/src/main/java/javafx/stage/Window.java

STEPS TO FOLLOW TO REPRODUCE THE PROBLEM :
Use org.controlsfx.samples.HelloNotifications from https://github.com/controlsfx/controlsfx/blob/master/controlsfx-samples/src/main/java/org/controlsfx/samples/HelloNotifications.java and press very frequent on "Top-right notification" then the NPE will occur. It is independent of the os. We tested it on windows and mac.

JDK-8221987: javafx.graphics/javafx.stage.Window$TKBoundsConfigurator.apply (#408)          

---

build.properties

This PR is targeted for the following bugs,
[JDK-8221300](https://bugs.openjdk.java.net/browse/JDK-8221300): Upgrade to Xcode 10.1
[JDK-8221302](https://bugs.openjdk.java.net/browse/JDK-8221302): Upgrade to gcc 8.2 on Linux
[JDK-8221299](https://bugs.openjdk.java.net/browse/JDK-8221299): Upgrade to Visual Studio 2017 version 15.9.6

Upgrade toolchains

---

modules/javafx.graphics/src/main/java/com/sun/glass/ui/Window.java
modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/WindowStage.java
modules/javafx.graphics/src/main/native-glass/win/GlassWindow.cpp

Related bug reports:
https://bugs.openjdk.java.net/browse/JDK-8089296, https://bugs.openjdk.java.net/browse/JDK-8088717, https://bugs.openjdk.java.net/browse/JDK-8134658, possibly https://bugs.openjdk.java.net/browse/JDK-8127270
Solution is based off http://stackoverflow.com/questions/26972683/javafx-minimizing-undecorated-stage
I had to add Window.MODAL because we need to know if transparent/undecorated windows should have the ability to minimize/restore by clicking the taskbar. It could've been done by adding  MINIMIZABLE to the mask in WindowStage.java, however without the ability to test that modification on other platforms, the safest thing was to add a new flag. Also, MINIMIZABLE and MAXIMIZABLE and CLOSABLE are derived, and not directly settable. It probably makes sense going …

8088717: Taskbar iconification of undecorated windows in Windows

---

SANDBOX-FILES.md

As indicated by the title of this PR, this adds a new file which contains a list of files that are in the `master` and `develop` branches of the `javafxports/openjdk-jfx` sandbox repo, but are not in the upstream [hg.openjdk.java.net/openjfx/jfx-dev/rt](https://hg.openjdk.java.net/openjfx/jfx-dev/rt) HG repo. This new file, `SANDBOX-FILES.md`, is itself in the list.

Add SANDBOX-FILES.md to list the set of "sandbox-only" files.

---

modules/javafx.web/src/main/native/Source/WTF/wtf/Optional.h

It is been already addressed in https://trac.webkit.org/changeset/235661.
We just need to cherry-pick the above changeset from upstream WebKit repo.
JBS link: https://bugs.openjdk.java.net/browse/JDK-8222788
It will address the issue #439 .

JDK-8222788: javafx.web build fails on XCode 10.2

---

modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java

This is an attempt to implement the change of the load order
of the native libraries as described in JDK-8223377.
The first commit refactors the library loading code into distinct
methods per loading variant. That commit does not change the
behavior of the library loading. Based on the refactored method,
the second commit implements to reordering.
For the legal part: I have an OCA on file

JDK-8223377: JavaFX can crash due to loading the wrong native libraries if system libraries are installed

---

modules/javafx.graphics/src/main/native-glass/win/GlassWindow.cpp

On Windows, a beep sound always plays when using accelerators/mnemonics with the alt key, even if those accelerators exist. It's only supposed to beep when no such key combination is registered (alt+L vs alt+F for example)
I've found a solution which never beeps which I believe is preferable. https://github.com/DeanWookey/openjdk-jfx/commit/3f8520e22f5090a35097005254133f2eac8f97cc, based on this stack overflow post: https://stackoverflow.com/questions/3662192/disable-messagebeep-on-invalid-syskeypress
Javafx on windows doesn't support the windows system menu, as seen in WinApplication which doesn't override the _supportsSystemMenu() method and returns false. The f10 and alt+f10 events are also prevented from being processed by Windows. 
`                if (wParam == VK_MENU || (wParam == …

8089986: Removed beeping when alt+key is pressed on Windows

---

modules/javafx.controls/src/main/java/javafx/scene/control/skin/VirtualFlow.java
modules/javafx.controls/src/shims/java/javafx/scene/control/skin/VirtualFlowShim.java
modules/javafx.controls/src/test/java/test/javafx/scene/control/skin/VirtualFlowTest.java

https://bugs.openjdk.java.net/browse/JDK-8197536
As pointed out in the bug it was introduced when VirtualFlow moved to the public scope. There was a special case for scrolling up/down one cell that was removed.
This fix restores the special case, that is more precise than the 0 to 1 relative position on the virtual flow.
The 0 to 1 (0% to 100%) position of the vertical scroll is not cell height precise, so the special case is needed for "move one cell up" ou "move one cell down". (specially with long lists).
Is a test case doable?

JDK-8197536: TableView, ListView: unexpected scrolling behaviour on up/down keys

---

modules/javafx.graphics/src/main/java/com/sun/glass/ui/win/WinWindow.java
tests/system/src/test/java/test/javafx/stage/MultipleScreensTest.java

https://bugs.openjdk.java.net/browse/JDK-8226274
As indicated in the JBS bug, this is a regression introduced by the fix for [JDK-8146920](https://bugs.openjdk.java.net/browse/JDK-8146920). On the Windows platform, when a `Stage` is moved (or initially shown) on a screen other than the one it was one (or other than the default when first showing the Stage), the `View` associated with the `Stage` is notified via a call to `view.updateLocation()`. However, the `view` is null until a scene is set on the stage. The simple, and correct fix is to add a null check.
I also created an automated test based on the test case provided in [JDK-8226274](https://bugs.openjdk.java.net/browse/JDK-8226274). The test is skipped when run on a system with only one monitor. It catches the bug without the fix …

JDK-8226274: NPE in WinWindow.notifyMoving when Stage with no Scene is shown on 2nd monitor

---

build.gradle
modules/javafx.graphics/src/jslc/antlr/com/sun/scenario/effect/compiler/JSL.g4
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/JSLC.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/ES2Backend.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/GLSLBackend.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/HLSLBackend.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/SLBackend.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/prism/PrismBackend.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/sw/java/JSWBackend.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/sw/me/MEBackend.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/sw/sse/SSEBackend.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/tree/CallExpr.java
modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/tree/JSLVisitor.java
modules/javafx.graphics/src/main/jsl-prism/CompileJSL.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/AddExprTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/AssignmentExprTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/EqualityExprTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/ExternalDeclarationTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/FieldSelectTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/FullySpecifiedTypeTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/IterationStatementTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/JumpStatementTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/MultExprTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/ParserBase.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/PrimaryExprTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/RelationalExprTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/SelectionStatementTest.java
modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/UnaryExprTest.java

We can do this in antlr4 by using the new visitor mechanism. Keeping
the grammar definition separate from the logic (embedded actions) "promotes the separation
of concerns between parsing and parser application". It also makes the
grammar easier to read and understand.
This PR takes a direct approach to extracting the embedded actions and does not change the end results of a generated shader. That is, a shader generated with JSLC before this PR and after will be identical. Here is an example of such a migration (for the `unary_expression` rule):
Before this PR `unary_expression` is defined as a mixture of grammar and embedded actions (the parts in curly braces):
```
unary_expression returns [Expr expr]
: p=postfix_expression     { $expr = $p.expr; }
| INC   u=unary_expression { $expr = …
```

JDK-8221269: Extract embedded actions from JSL grammar file to Visitor class

---

build.properties
modules/javafx.base/src/test/java/test/com/sun/javafx/runtime/VersionInfoTest.java

[JDK-8226365](https://bugs.openjdk.java.net/browse/JDK-8226365)
The JavaFX 13-dev repo will be forked from jfx-dev tomorrow morning, after which, we need to bump the release version to 14. As such, I will wait until tomorrow to send out the formal RFR and remove the WIP label.

JDK-8226365: Change JavaFX release version to 14

---

modules/javafx.web/src/main/native/Source/WebCore/Sources.txt
modules/javafx.web/src/main/native/Source/WebCore/platform/network/NetworkStorageSession.h
modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/NetworkStorageSessionJava.cpp
modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/SocketStreamHandleImpl.h
modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/SocketStreamHandleImplJava.cpp
modules/javafx.web/src/main/native/Source/WebKitLegacy/PlatformJava.cmake
modules/javafx.web/src/main/native/Source/WebKitLegacy/java/WebCoreSupport/FrameNetworkingContextJava.h

Root cause:
`SocketStreamHandleImpl::platformSendHandshake` is not implemented.
Solution:
SocketStreamHandleImpl.cpp already has boilerplate implementation and used by other WebKit ports as well. Switch to the above mentioned implementation and provide only platform specific functionality like connect, send, receive and close. 
JBS link: https://bugs.openjdk.java.net/browse/JDK-8222912

JDK-8222912: Websocket client doesn't work in WebView

---

modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/SpinnerBehavior.java
modules/javafx.controls/src/main/java/javafx/scene/control/skin/SpinnerSkin.java
modules/javafx.controls/src/test/java/test/javafx/scene/control/SpinnerTest.java

Added basic check for up/down keys in the KeyEvent filters when Spinner behaviour indicates the arrows are vertical.  Had to make a private method in SpinnerBehavior public to keep the vertical arrow check in one spot.

8185937: Editable Spinner up/down keys do not increment/decrement

---

UPDATING-VERSION.md

JBS issue: [JDK-8193911](https://bugs.openjdk.java.net/browse/JDK-8193911)
This PR adds a new `UPDATING-VERSION.md` file to the repo with instruction for bumping the JavaFX version number, either for a feature release (13 to 14 to 15) or for a security release (13 to 13.0.1 to 13.0.2).

JDK-8193911: Create README file to document bumping the version number

---

.github/CONTRIBUTING.md
.github/README.md

This PR is a simple follow-up fix to PR #526.
Note that there is no corresponding JBS bug ID because this PR is touching GitHub [sandbox-only](https://github.com/javafxports/openjdk-jfx/blob/develop/SANDBOX-FILES.md) files exclusively.
This PR applies the following changes from PR #526 to the `.github/` copies of `README.md` and `CONTRIBUTING.md`.
1. Change all occurrences of `http://` to `https://` in both `README.md` and `CONTRIBUTING.md`
2. Add a pointer to the `openjfx.io` community site to `README.md`
3. Incorporate the minor wording change to `README.md` for first-time contributors.
All of the above changes were reviewed as part of PR #526 so the main purpose of this review is to make sure that no errors crept in while applying the relevant parts of that patch.

Update .github copy of README.md and CONTRIBUTING.md

---

.gitignore

JBS issue: [JDK-8223722](https://bugs.openjdk.java.net/browse/JDK-8223722)
Simple fix to cleanup the `.gitignore` file and add a few useful missing patterns.
As a help to reviewers, I pushed two commits:
1. Fix/add comments and reorganize the existing patterns without adding or removing any patterns
2. Add new patterns / modify existing patterns
If you want to see what was actually changed (as opposed to reordered), you can just look at the second commit.

JDK-8223722: Cleanup .gitignore file

---

modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DContext.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DGraphics.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DMesh.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DMeshView.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DPhongMaterial.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DPipeline.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DRTTexture.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DResource.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DResourceFactory.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DShader.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DSwapChain.java
modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DTexture.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Graphics.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Mesh.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2MeshView.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2PhongMaterial.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2RTTexture.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2ResourceFactory.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Shader.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2SwapChain.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Texture.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2TextureData.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/GLFactory.java
modules/javafx.graphics/src/main/java/com/sun/prism/es2/GLPixelFormat.java

Very simple PR that adds missing `@Override` annotations to classes in `javafx.graphics/src/main/java/com/sun/prism/*`. This is always good practice but in this specific case it will help anyone trying to implement a new rendering pipeline (Vulkan, DirectX 11/12, etc.) as it makes it easier to see what methods are required to be implemented as they are used by Prism and which methods are implementation details.
I also took the liberty to fix a couple places where a static method was being called on an instance of a class and make the formatting of the empty `traceDispose` methods consistent (putting opening and closing curly brackets on same line).

JDK-8227367 Add missing @Override's and fix static usage.

---

modules/javafx.web/src/main/native/Source/JavaScriptCore/llint/LLIntData.h
modules/javafx.web/src/main/native/Source/WebCore/bindings/js/CommonVM.cpp

JBS bug: https://bugs.openjdk.java.net/browse/JDK-8227431
Follow on to PR #525 
Includes PR 525 + nullptr check for C_LOOP (i.e only for x86 build).

JDK-8227431: [Windows] Fix assertion failure on X86 32-bit when enabling CLOOP based JavaScript interpreter

---

modules/javafx.graphics/src/main/java/javafx/application/Platform.java
modules/javafx.graphics/src/main/native-glass/mac/GlassApplication.m
tests/system/src/test/java/test/com/sun/javafx/application/ConcurrentStartupTest.java
tests/system/src/test/java/test/com/sun/javafx/application/StaticStartupTest.java

allow main thread to continue before calling the runnable that is provided with Platform.startup().
This fixes #542 or JDK-8228766

JDK-8228766: [Mac] fix deadlock in platform.startup(Runnable r)

---

modules/javafx.base/src/main/java/com/sun/javafx/binding/SelectBinding.java

Fix for bug JDK-8220396
See https://bugs.openjdk.java.net/browse/JDK-8220396 and
https://github.com/javafxports/openjdk-jfx/issues/383
Attached is a new standalone test program which verifies that the fix works and that other errors are still reported as before. I could not test the else-part of the exception handler because I did not find any condition where this is executed.
[NewBindingsEval.java.zip](https://github.com/javafxports/openjdk-jfx/files/3464919/NewBindingsEval.java.zip)

JDK-8220396: Bindings class gives a lot of unneeded 'select-binding' log messages

---

modules/javafx.web/src/main/native/Source/WTF/wtf/FileSystem.h

On Windows platform PlatformFileHandle type is considered as HANDLE (i.e void *) which is specific to Windows flavor of webkit port. 
For OpenJFX, type of PlatformFileHandle should be JGObject. 
Due to this failure, randomly (at times) the type of FileHandle returned from native webkit will be other than java.io.RandomAccessFile

JDK-8229328: [windows] PlatformFileHandle type should be JGObject rather than void*

---

modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/skin/Utils.java
modules/javafx.controls/src/main/java/javafx/scene/control/skin/MenuButtonSkinBase.java
tests/system/src/test/java/test/javafx/scene/control/MenuButtonSkinBaseNPETest.java

Hi! This is a follow-up PR for issue https://github.com/javafxports/openjdk-jfx/issues/465
I signed OCA (received welcome letter from @kevinrushforth on 26th of July).
I managed to create a stable repro case, see `MenuButtonSkinBaseNPETest.java`.
Most important lines in repro are 45-46:
```java
menu.hide();
menuBar.getMenus().clear();
```
When you hide menu which is in a menu bar, it scheduled mnemonics removal in runLater:
```java
Platform.runLater(() -> Utils.removeMnemonics(popup, getSkinnable().getScene()));
```
But when you clear said menu bar, it disposes all menus, which leaded to all sorts of exceptions: `getSkinnable` in MenuButtonSkinBase becomes null, but also popup's skin becomes null (and we access it later in `Utils::removeMnemonics`).
The fix is to save added mnemonics to a …

JDK-8179097: Fix NPE on removing mnemonics of disposed popup

---

modules/javafx.web/src/main/native/Source/WebKitLegacy/java/WebCoreSupport/WebPage.cpp
modules/javafx.web/src/test/java/test/javafx/scene/web/MiscellaneousTest.java

Cookiejar Object didn't had valid StorageSessionProvider object, This was due to fix in webkit https://trac.webkit.org/changeset/240014/webkit.
Solution : Create CookieJar with PageStorageSessionProvider (with Page Ref) and add to Page Configuration. 
Test : Load https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_nav_cookieenabled and check for "Cookies enabled: true"

JDK-8230361: [web] Cookies are not enabled in WebKit v608.1

---

modules/javafx.graphics/src/main/java/com/sun/javafx/sg/prism/NGRegion.java

ticket: https://github.com/javafxports/openjdk-jfx/issues/379
Fixed poor printing quality for Regions.
The Printer uses vector graphics when possible.
By avoiding caching for Region we ensure high printing quality.
The printing quality is low when effects are used.
In this case, the printer must render pixels.
Ideally, JavaFX would handle printing pixels like rendering on a 4k monitor - by simulating a very high resolution.
But this is not part of the pull request.

JDK-8166194: Poor printing quality

---

modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/TextFieldBehavior.java
modules/javafx.controls/src/test/java/test/javafx/scene/control/TextFieldTest.java

This is a (limited, see below) fix for https://bugs.openjdk.java.net/browse/JDK-8207774. 
The issue is that the keyPressed of ENTER on the TextField is forwarded up the parent chain, even if an actionHandler consumed the fired action. The technical reason is that the action may be copied during dispatch, such that the action that's consumed is a different instance than the instance that's sent. If that happens, the consumed state of the sent action will always be false.
This change sends an actionEvent with the textField as eventTarget - doing so prevents the _immediate_ copy of the action. 
To test the change, the sample code in the bug report was converted to two fixtures in TextFieldTest - they failed before the change and pass after.
Limitation: the actionEvent may be copied elsewhere …

JDK-8207774: TextField must not forward ENTER if action consumed

---

modules/javafx.web/src/main/legal/libxslt.md

JBS bug: [JDK-8231126](https://bugs.openjdk.java.net/browse/JDK-8231126)
Simple fix to re-apply the correct version number string in the `/legal/libxslt.md` file, which was inadvertently reverted by the fix for [JDK-8222746](https://bugs.openjdk.java.net/browse/JDK-8222746).

8231126: libxslt.md has incorrect version string
